insert into public.formation_poles (id, slug, name, tagline, description, sort_order) values
('numerique-it', 'numerique-it', 'Numérique & IT', 'Construire, maintenir et faire évoluer les systèmes.', 'Développement, maintenance, données et transformation digitale.', 1),
('cybersecurite', 'cybersecurite', 'Cybersécurité', 'Protéger les réseaux, les systèmes et l’information.', 'Administration, sécurité des réseaux et audit des systèmes d’information.', 2),
('gestion-administration', 'gestion-administration', 'Gestion & Administration', 'Piloter l’activité, les dossiers et la relation client.', 'Secrétariat, gestion, commerce, marketing digital et gouvernance.', 3),
('creatif-service', 'creatif-service', 'Métiers créatifs & de service', 'Donner forme à l’image, au son et au mouvement.', 'Infographie, montage audiovisuel et motion design.', 4),
('sante-qhse-social', 'sante-qhse-social', 'Santé, QHSE & Social', 'Soin, qualité, hygiène, sécurité et environnement.', 'Filières liées à la santé de proximité et à la maîtrise des risques.', 5);

insert into public.formations (id, pole_id, slug, title, diploma, duration, sort_order) values
('developpement-web-mobile', 'numerique-it', 'developpement-web-mobile', 'Développement web et mobile', 'dqp', '1 an', 1),
('developpement-mern', 'numerique-it', 'developpement-mern', 'Développement d’application web full stack MERN', 'dqp', '1 an', 2),
('technologies-web-avancees', 'numerique-it', 'technologies-web-avancees', 'Technologies web avancées', 'dqp', '1 an', 3),
('webmaster', 'numerique-it', 'webmaster', 'Webmaster', 'cqp', '1 an', 4),
('developpement-applications-mobiles', 'numerique-it', 'developpement-applications-mobiles', 'Développement des applications mobiles', 'dqp', '1 an', 5),
('genie-logiciel', 'numerique-it', 'genie-logiciel', 'Génie logiciel', 'dqp', '1 an', 6),
('analyse-conception-systemes', 'numerique-it', 'analyse-conception-systemes', 'Analyse et conception des systèmes', 'dqp', '1 an', 7),
('maintenance-systemes-reseaux', 'numerique-it', 'maintenance-systemes-reseaux', 'Maintenance des systèmes et réseaux informatiques', 'cqp', '1 an', 8),
('analyse-des-donnees', 'numerique-it', 'analyse-des-donnees', 'Analyse des données', 'dqp', '1 an', 9),
('business-intelligence', 'numerique-it', 'business-intelligence', 'Business intelligence', 'dqp', '1 an', 10),
('internet-des-objets', 'numerique-it', 'internet-des-objets', 'Internet des objets (IoT)', 'dqp', '1 an', 11),
('intelligence-artificielle', 'numerique-it', 'intelligence-artificielle', 'Intelligence artificielle', 'dqp', '1 an', 12),
('administration-bases-de-donnees', 'numerique-it', 'administration-bases-de-donnees', 'Administration et optimisation des bases de données', 'dqp', '1 an', 13),
('bases-de-donnees-avancees', 'numerique-it', 'bases-de-donnees-avancees', 'Bases de données avancées', 'dqp', '1 an', 14),
('transformation-digitale', 'numerique-it', 'transformation-digitale', 'Transformation digitale', 'cqp', '1 an', 15),
('veille-technologique', 'numerique-it', 'veille-technologique', 'Veille technologique', 'cqp', '1 an', 16),
('systemes-intelligents', 'numerique-it', 'systemes-intelligents', 'Systèmes intelligents', 'dqp', '1 an', 17),
('gestion-projet-informatique', 'numerique-it', 'gestion-projet-informatique', 'Gestion de projet informatique', 'cqp', '1 an', 18),
('supervision-systemes-information', 'numerique-it', 'supervision-systemes-information', 'Supervision des systèmes d’information', 'dqp', '1 an', 19),
('architecte-gestion-cybersecurite', 'cybersecurite', 'architecte-gestion-cybersecurite', 'Architecte et gestion de la cybersécurité', 'dqp', '1 an', 20),
('analyse-cybersecurite', 'cybersecurite', 'analyse-cybersecurite', 'Analyse et cybersécurité', 'dqp', '1 an', 21),
('administration-systemes-reseaux', 'cybersecurite', 'administration-systemes-reseaux', 'Administration systèmes et réseaux', 'cqp', '1 an', 22),
('securite-reseaux', 'cybersecurite', 'securite-reseaux', 'Sécurité et réseaux', 'cqp', '1 an', 23),
('securite-systemes-information', 'cybersecurite', 'securite-systemes-information', 'Sécurité des systèmes d’information', 'dqp', '1 an', 24),
('audit-controle-systemes', 'cybersecurite', 'audit-controle-systemes', 'Audit et contrôle des systèmes informatiques', 'dqp', '1 an', 25),
('secretariat-comptable', 'gestion-administration', 'secretariat-comptable', 'Secrétariat comptable', 'cqp', '1 an', 26),
('secretariat-bureautique-bilingue', 'gestion-administration', 'secretariat-bureautique-bilingue', 'Secrétariat bureautique bilingue', 'cqp', '1 an', 27),
('assistante-direction-bilingue', 'gestion-administration', 'assistante-direction-bilingue', 'Secrétariat assistante de direction bilingue', 'cqp', '1 an', 28),
('entreprenariat', 'gestion-administration', 'entreprenariat', 'Entreprenariat', 'cqp', '1 an', 29),
('architecture-entreprise', 'gestion-administration', 'architecture-entreprise', 'Architecture d’entreprise', 'dqp', '1 an', 30),
('e-business-marketing-digital', 'gestion-administration', 'e-business-marketing-digital', 'E-business et marketing digital', 'cqp', '1 an', 31),
('finance', 'gestion-administration', 'finance', 'Finance', 'cqp', '1 an', 32),
('audit-fiscal', 'gestion-administration', 'audit-fiscal', 'Audit fiscal', 'dqp', '1 an', 33),
('commerce-vente', 'gestion-administration', 'commerce-vente', 'Commerce et vente', 'cqp', '1 an', 34),
('management-gouvernance', 'gestion-administration', 'management-gouvernance', 'Management et gouvernance d’entreprise', 'dqp', '1 an', 35),
('infographie', 'creatif-service', 'infographie', 'Infographie', 'cqp', '1 an', 36),
('montage-audiovisuel', 'creatif-service', 'montage-audiovisuel', 'Montage audiovisuel', 'cqp', '1 an', 37),
('motion-design', 'creatif-service', 'motion-design', 'Motion design', 'cqp', '1 an', 38),
('vente-en-pharmacie', 'sante-qhse-social', 'vente-en-pharmacie', 'Vente en pharmacie', 'cqp', '1 an', 39),
('qhse', 'sante-qhse-social', 'qhse', 'Gestion qualité, hygiène, sécurité et environnement', 'dqp', '1 an', 40);
